ActiveAdmin::Editor.configure do |config|
  # config.s3_bucket = ''
  # config.aws_access_key_id = ''
  # config.aws_access_secret = ''
  # config.storage_dir = 'uploads'
  config.parser_rules["classes"]['wysiwyg-clear-both'] = 1
  config.parser_rules["classes"]['wysiwyg-clear-left'] = 1
  config.parser_rules["classes"]['wysiwyg-clear-right'] = 1
  config.parser_rules["classes"]['wysiwyg-color-aqua'] = 1
  config.parser_rules["classes"]['wysiwyg-color-black'] = 1
  config.parser_rules["classes"]['wysiwyg-color-blue'] = 1
  config.parser_rules["classes"]['wysiwyg-color-fuchsia'] = 1
  config.parser_rules["classes"]['wysiwyg-color-gray'] = 1
  config.parser_rules["classes"]['wysiwyg-color-green'] = 1
  config.parser_rules["classes"]['wysiwyg-color-lime'] = 1
  config.parser_rules["classes"]['wysiwyg-color-maroon'] = 1
  config.parser_rules["classes"]['wysiwyg-color-navy'] = 1
  config.parser_rules["classes"]['wysiwyg-color-olive'] = 1
  config.parser_rules["classes"]['wysiwyg-color-purple'] = 1
  config.parser_rules["classes"]['wysiwyg-color-red'] = 1
  config.parser_rules["classes"]['wysiwyg-color-silver'] = 1
  config.parser_rules["classes"]['wysiwyg-color-teal'] = 1
  config.parser_rules["classes"]['wysiwyg-color-white'] = 1
  config.parser_rules["classes"]['wysiwyg-color-yellow'] = 1
  config.parser_rules["classes"]['wysiwyg-float-left'] = 1
  config.parser_rules["classes"]['wysiwyg-float-right'] = 1
  config.parser_rules["classes"]['wysiwyg-font-size-large'] = 1
  config.parser_rules["classes"]['wysiwyg-font-size-larger'] = 1
  config.parser_rules["classes"]['wysiwyg-font-size-medium'] = 1
  config.parser_rules["classes"]['wysiwyg-font-size-small'] = 1
  config.parser_rules["classes"]['wysiwyg-font-size-smaller'] = 1
  config.parser_rules["classes"]['wysiwyg-font-size-x-large'] = 1
  config.parser_rules["classes"]['wysiwyg-font-size-x-small'] = 1
  config.parser_rules["classes"]['wysiwyg-font-size-xx-large'] = 1
  config.parser_rules["classes"]['wysiwyg-font-size-xx-small'] = 1
  config.parser_rules["classes"]['wysiwyg-text-align-center'] = 1
  config.parser_rules["classes"]['wysiwyg-text-align-justify'] = 1
  config.parser_rules["classes"]['wysiwyg-text-align-left'] = 1
  config.parser_rules["classes"]['wysiwyg-text-align-right'] = 0
end
